{% set version = "1.9.22" %}

package:
  name: jack
  version: {{ version }}

source:
  url: https://github.com/jackaudio/jack2/archive/v{{ version }}.tar.gz
  sha256: 1e42b9fc4ad7db7befd414d45ab2f8a159c0b30fcd6eee452be662298766a849
  patches:
    # pick up the proper version of Python
    - waf.patch

build:
  number: 2
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_subpackage('jack', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - python >=3.6,<3.11
    - pkg-config
  host:
    - libdb
    - alsa-lib
    - alsa-lib >=1.0.18
    - libopus
    - eigen >=3.1.2
    - portaudio  # [win]
  run:
    - libdb

test:
  commands:

about:
  home: http://jackaudio.org/
  license: LGPL-2.0-only
  license_file: COPYING
  summary: Audio connection kit.

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
    - ryanvolz
