{% set version = "1.9.19" %}

package:
  name: jack
  version: {{ version }}

source:
  url: https://github.com/jackaudio/jack2/archive/v{{ version }}.tar.gz
  sha256: 9030f4dc11773351b6ac96affd9c89803a5587ebc1b091e5ff866f433327e4b0
  patches:
    # pick up the proper version of Python
    - waf.patch
    # https://git.kx.studio/jackaudio/jack2/commit/9fe56af980e4a7279cfe826a2b1f8bf1f799763a
    - common-jackapi.cpp.patch

build:
  number: 0
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_subpackage('jack', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python >=3.6
    - pkg-config
  host:
    - libdb
    - alsa-lib >=1.0.18
    - libsndfile
    - readline
    - libopus
    - eigen >=3.1.2
    - portaudio
  run:
    - libdb

test:
  commands:

about:
  home: http://jackaudio.org/
  license: LGPL-2.0-only
  license_file: COPYING
  summary: Audio connection kit.

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
